# Generated by Django 2.0.6 on 2018-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_url', models.CharField(max_length=30, verbose_name='Git地址')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('excel_conf', models.FileField(upload_to='./upload', verbose_name='配置文件')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
