# Generated by Django 2.0.6 on 2018-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180620_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['last_use']},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='excel_conf',
        ),
        migrations.AddField(
            model_name='testcase',
            name='commit_id',
            field=models.CharField(default='latest', max_length=30, verbose_name='Commit ID'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='last_use',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次执行'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_case',
            field=models.FileField(default=2, upload_to='./upload', verbose_name='测试用例'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='use_count',
            field=models.IntegerField(default=0, verbose_name='执行次数'),
        ),
    ]
