# Generated by Django 2.0.6 on 2018-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180620_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='user_name',
            field=models.CharField(default='', max_length=30, verbose_name='用户名'),
        ),
    ]
