# Generated by Django 2.0.6 on 2018-06-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_testcase_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['last_use'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
    ]
